# Generated by Django 5.0.3 on 2024-03-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
